export const RESIDENTIAL_SINGLE_CAMERA_OPEN = 'RESIDENTIAL_SINGLE_CAMERA_OPEN';
export const RESIDENTIAL_SINGLE_CAMERA_CLOSE = 'RESIDENTIAL_SINGLE_CAMERA_CLOSE';
export const RESIDENTIAL_SINGLE_FORM_OPEN = 'RESIDENTIAL_SINGLE_FORM_OPEN';
export const RESIDENTIAL_SINGLE_FORM_CLOSE = 'RESIDENTIAL_SINGLE_FORM_CLOSE';

export const RESIDENTIAL_SINGLE_FETCH_DATA_REQUEST = 'RESIDENTIAL_SINGLE_FETCH_DATA_REQUEST';
export const RESIDENTIAL_SINGLE_FETCH_DATA_SUCCESS = 'RESIDENTIAL_SINGLE_FETCH_DATA_SUCCESS';
export const RESIDENTIAL_SINGLE_FETCH_DATA_ERROR = 'RESIDENTIAL_SINGLE_FETCH_DATA_ERROR';
export const RESIDENTIAL_SINGLE_CLEAR_DATA = 'RESIDENTIAL_SINGLE_CLEAR_DATA';