export const FOOTER_FETCH_CONTACT_REQUEST = 'FOOTER_FETCH_CONTACT_REQUEST';
export const FOOTER_FETCH_CONTACT_SUCCESS = 'FOOTER_FETCH_CONTACT_SUCCESS';
export const FOOTER_FETCH_SOCIAL_ICON = 'FOOTER_FETCH_SOCIAL_ICON';
export const FOOTER_FETCH_CONTACT_ERROR = 'FOOTER_FETCH_CONTACT_ERROR';