export const HEADER_CHANGE_LANGUAGE = 'HEADER_CHANGE_LANGUAGE';
export const HEADER_GET_NAME_ITEM_MENU = 'HEADER_GET_NAME_ITEM_MENU';
export const HEADER_GET_CURRENT_CATEGORY = 'HEADER_GET_CURRENT_CATEGORY';
export const SET_CURRENT_CITY_FROM_LOCATION = 'SET_CURRENT_CITY_FROM_LOCATION';
export const SET_CURRENT_INDEX_CATEGORIES = 'SET_CURRENT_INDEX_CATEGORIES';